spring:
  application:
    name: service2
  h2:
    console:
      enabled: true
      path: /console2
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
